version: '3'
services:
  kulkan-eko-2023-ctf-challenge:
    image: eko-ctf-kulkan-2023:latest
    ports:
      - "12000:12000"
    networks:
      - messi-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - messi-network
    depends_on:
      - kulkan-eko-2023-ctf-challenge
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - messi-network
    depends_on:
      - nginx

networks:
  messi-network:
    #external: true
